version: '3'
services:
  notificationofcouponsserver:
    build: ./
    container_name: notificationofcouponsserver
    restart: always
    ports:
      - 8089:8089
    volumes:
      - ./:/app
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27019:27017
    volumes:
      - ./mongo-data:/data/db
